### ISSUE TITLE
비밀번호 검사 이슈

### ISSUE THREAD

**Issue by pmsu2007** [100-hours-a-week/2-jeonggu-kim-community-issue#20]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:

**예상한 동작**
비밀번호와 비밀번호 확인이 일치한 상황에서 비밀번호에 추가적으로 입력할 경우 틀렸다는 Helper Message를 예상했음

**스크린샷**
![image](https://github.com/user-attachments/assets/6889cacd-757a-4c59-a669-8479c40f1c95)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by dev-jeonggu** [comment]
혹시 위에는 어떤 값을 입력하고, 아래는 어떤 값을 입력하신건지 알 수 있을까요?

**Comment by pmsu2007** [comment]
> 혹시 위에는 어떤 값을 입력하고, 아래는 어떤 값을 입력하신건지 알 수 있을까요?

비밀번호 : qwer1234!
비밀번호 확인 : qwer1234!

이 상태에서

비밀번호 : qwer1234!12 

비밀번호만 변경했을 때 비밀번호가 다르다는 Helper Message를 예상했습니다.

**Comment by dev-jeonggu** [comment]
@pmsu2007 사이트에서 유효성 검사를 입력하면 change될 때마다 진행하는 것이 아니라 blur 처리가 되었을 때 진행합니다. 혹시 blur처리가 되었을 때도 이러한 현상이 발견되는 걸까요?? 제가 진행해보았을 때는 blur 처리가 되지 않은 상태에서 회원가입을 눌렀을 때도 hepler-text가 작동합니다. 해당 부분은 확인 부탁드립니다.

**Comment by dev-jeonggu** [comment]
해당 이슈는 현재 유효성 검사가 잘 이루어지고 있으며 change 진행시가 아닌, blur 처리시에 유효성 검사가 이루어지고 있습니다. 추후에 해당 이슈 관련해서 더 나온다면 그때 다른 방식으로 처리하도록 하겠습니다. 감사합니다. 🐐
