### ISSUE TITLE
우측 상단 프로필 이미지 안뜨는 현상 

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-jeonggu-kim-community-issue#3]
**버그 설명**
게시글 목록 창에서 프로필 이미지가 뜨지 않습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 목록 창 접근

**예상한 동작**
프로필 이미지가 보여야함

**스크린샷**
문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
![image](https://github.com/user-attachments/assets/4dc22ea1-85fc-4c1c-83dd-301848166073)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요)**

**추가적인 내용**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by dev-jeonggu** [comment]
우측 프로필 사진은 의도적으로 노출하지 않았습니다. 디자인 통일성을 위해 구름 이미지로 대체하였고, 이는 커뮤니티를 꾸미는 과정에서 개발자의 의도에 따른 결정입니다.

**Comment by dev-jeonggu** [comment]
혹시 이미지 사진이 보이지 않는게 불편하신가요??? 해당 부분이 의도된 부분이긴하나, 불편하신 부분이라면 고려해보겠습니다.

**Comment by happy-yeachan** [comment]
저는 배경과 구름이 동화되어 요소가 있는 건지 찾기 힘들었습니다!

**Comment by dev-jeonggu** [comment]
@happy-yeachan 프로필 사진으로 대체하진 않을 예정이라, 해당 부분 중에 선택해주시면 적용하겠습니다.
1.
<img width="430" alt="image" src="https://github.com/user-attachments/assets/1c0b91e3-ed28-4788-8099-2c0cadf37b61" />

2.
<img width="425" alt="image" src="https://github.com/user-attachments/assets/95581134-8240-4be9-a11a-07495b02d0c7" />

3.
<img width="420" alt="image" src="https://github.com/user-attachments/assets/092ea118-1a5c-4af7-b5cf-a5f572efdb57" />

**Comment by dev-jeonggu** [comment]
확인 감사합니다!
