### ISSUE TITLE
백엔드 서버 접근 가능 현상

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-jeonggu-kim-community-issue#9]
**버그 설명**
백엔드 서버 (http://43.203.15.108:3001/) 접근하면 로그인창? 이 뜸

**재현하는 방법**
동작을 재현하는 단계:
1. http://43.203.15.108:3001/ 접근

**예상한 동작**
aws 보안그룹에서 막힌다

**스크린샷**
문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="561" alt="image" src="https://github.com/user-attachments/assets/d295e1ff-921b-4e7f-95f3-18f660fb00cd" />

aws 보안그룹에서 프론트 서버와 db 서버에서만 백엔드 서버 접근이 가능하게 하는건 어떨까요?

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요)**

**추가적인 내용**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by dev-jeonggu** [comment]
해당 페이지를 막아둘 생각도 했었는데, 테스트 진행 시 fe, be 둘 다 진행을 할 수도 있을 것 같아서 일단 다 열어둔 상태입니다. QA가 끝나고 나서 해당 부분은 제한 하도록 하겠습니다. (그때 다시 이슈를 오픈하도록 하겠습니다.)

**Comment by dev-jeonggu** [comment]
QA가 끝나고 나서 해당 부분은 제한 하도록 하게습니다. 
(그때 다시 이슈를 오픈하도록 하겠습니다.)
